include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - generate
  - trigger

generate-pipeline:
  stage: generate
  extends: .container-runner-lightweight-zen2
  image: docker.io/python:3.12
  script:
    - pip install jinja2
    - >
      python3 ci/generate_pipeline.py
      24.07/gh200/gnu.yaml
      24.07/gh200/cray.yaml
      25.03/gh200/gnu.yaml
      25.03/gh200/cray.yaml
  artifacts:
    paths:
      - generated_pipeline.yml

trigger-cpe-build:
  stage: trigger
  trigger:
    forward:
      pipeline_variables: true
    include:
      - artifact: generated_pipeline.yml
        job: generate-pipeline
